var R=require("./chunks/[turbopack]_runtime.js")("server/instrumentation.js")
R.c("server/chunks/[externals]_node:inspector_dc347386._.js")
R.c("server/chunks/12e3c_@sentry_core_build_cjs_22a6c367._.js")
R.c("server/chunks/aa9db_@sentry_conventions_dist_c58757be._.js")
R.c("server/chunks/6b547_@sentry_nextjs_build_cjs_5dec1fbe._.js")
R.c("server/chunks/8e2ec_@sentry_server-utils_build_cjs_orchestrion_1302b872._.js")
R.c("server/chunks/8e2ec_@sentry_server-utils_build_cjs_vendored_524e6380._.js")
R.c("server/chunks/8e2ec_@sentry_server-utils_build_cjs_integrations_tracing-channel_557aa06f._.js")
R.c("server/chunks/8e2ec_@sentry_server-utils_build_cjs_edcc8846._.js")
R.c("server/chunks/f1100_@opentelemetry_api_build_esm_27988c76._.js")
R.c("server/chunks/b39a6_@sentry_node-core_build_cjs_36d18a42._.js")
R.c("server/chunks/b934d_@opentelemetry_sdk-trace_build_esm_812da58f._.js")
R.c("server/chunks/6fdad_@sentry_node_build_cjs_648a95a4._.js")
R.c("server/chunks/34c60__pnpm_26a9e93b._.js")
R.c("server/chunks/[root-of-the-server]__aad36cda._.js")
R.m("[project]/dograh-1/ui/src/instrumentation.ts [instrumentation] (ecmascript)")
module.exports=R.m("[project]/dograh-1/ui/src/instrumentation.ts [instrumentation] (ecmascript)").exports
