// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/after-sign-in" | "/agent-onboarding" | "/api-keys" | "/auth/login" | "/auth/signup" | "/automation" | "/billing" | "/campaigns" | "/campaigns/[campaignId]" | "/campaigns/[campaignId]/edit" | "/campaigns/new" | "/docs" | "/files" | "/handler/[...stack]" | "/model-configurations" | "/overview" | "/pilot" | "/recordings" | "/reports" | "/settings" | "/superadmin" | "/superadmin/runs" | "/telephony-configurations" | "/telephony-configurations/[configId]" | "/tools" | "/tools/[toolUuid]" | "/usage" | "/workflow" | "/workflow/[workflowId]" | "/workflow/[workflowId]/run/[runId]" | "/workflow/[workflowId]/runs" | "/workflow/[workflowId]/settings" | "/workflow/create"
type AppRouteHandlerRoutes = "/api/auth/logout" | "/api/auth/oss" | "/api/auth/session" | "/api/config/auth" | "/api/config/latest-version" | "/api/config/posthog" | "/api/config/sentry" | "/api/config/version" | "/api/v1/[...path]" | "/impersonate"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = "/ingest/[[...path]]" | "/ingest/decide" | "/ingest/static/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/after-sign-in": {}
  "/agent-onboarding": {}
  "/api-keys": {}
  "/api/auth/logout": {}
  "/api/auth/oss": {}
  "/api/auth/session": {}
  "/api/config/auth": {}
  "/api/config/latest-version": {}
  "/api/config/posthog": {}
  "/api/config/sentry": {}
  "/api/config/version": {}
  "/api/v1/[...path]": { "path": string[]; }
  "/auth/login": {}
  "/auth/signup": {}
  "/automation": {}
  "/billing": {}
  "/campaigns": {}
  "/campaigns/[campaignId]": { "campaignId": string; }
  "/campaigns/[campaignId]/edit": { "campaignId": string; }
  "/campaigns/new": {}
  "/docs": {}
  "/files": {}
  "/handler/[...stack]": { "stack": string[]; }
  "/impersonate": {}
  "/ingest/[[...path]]": { "path"?: string[]; }
  "/ingest/decide": {}
  "/ingest/static/[[...path]]": { "path"?: string[]; }
  "/model-configurations": {}
  "/overview": {}
  "/pilot": {}
  "/recordings": {}
  "/reports": {}
  "/settings": {}
  "/superadmin": {}
  "/superadmin/runs": {}
  "/telephony-configurations": {}
  "/telephony-configurations/[configId]": { "configId": string; }
  "/tools": {}
  "/tools/[toolUuid]": { "toolUuid": string; }
  "/usage": {}
  "/workflow": {}
  "/workflow/[workflowId]": { "workflowId": string; }
  "/workflow/[workflowId]/run/[runId]": { "workflowId": string; "runId": string; }
  "/workflow/[workflowId]/runs": { "workflowId": string; }
  "/workflow/[workflowId]/settings": { "workflowId": string; }
  "/workflow/create": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
