// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/after-sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/after-sign-in">> = Specific
  const handler = {} as typeof import("../../src/app/after-sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agent-onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent-onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/agent-onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/api-keys">> = Specific
  const handler = {} as typeof import("../../src/app/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signup">> = Specific
  const handler = {} as typeof import("../../src/app/auth/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/automation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/automation">> = Specific
  const handler = {} as typeof import("../../src/app/automation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing">> = Specific
  const handler = {} as typeof import("../../src/app/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/campaigns/[campaignId]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/campaigns/[campaignId]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/campaigns/[campaignId]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/campaigns/[campaignId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/campaigns/[campaignId]">> = Specific
  const handler = {} as typeof import("../../src/app/campaigns/[campaignId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/campaigns/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/campaigns/new">> = Specific
  const handler = {} as typeof import("../../src/app/campaigns/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/campaigns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/campaigns">> = Specific
  const handler = {} as typeof import("../../src/app/campaigns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../src/app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/files/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/files">> = Specific
  const handler = {} as typeof import("../../src/app/files/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/handler/[...stack]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/handler/[...stack]">> = Specific
  const handler = {} as typeof import("../../src/app/handler/[...stack]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/model-configurations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/model-configurations">> = Specific
  const handler = {} as typeof import("../../src/app/model-configurations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/overview">> = Specific
  const handler = {} as typeof import("../../src/app/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pilot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pilot">> = Specific
  const handler = {} as typeof import("../../src/app/pilot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recordings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recordings">> = Specific
  const handler = {} as typeof import("../../src/app/recordings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../src/app/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/superadmin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin">> = Specific
  const handler = {} as typeof import("../../src/app/superadmin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/superadmin/runs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin/runs">> = Specific
  const handler = {} as typeof import("../../src/app/superadmin/runs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/telephony-configurations/[configId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telephony-configurations/[configId]">> = Specific
  const handler = {} as typeof import("../../src/app/telephony-configurations/[configId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/telephony-configurations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telephony-configurations">> = Specific
  const handler = {} as typeof import("../../src/app/telephony-configurations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tools/[toolUuid]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/[toolUuid]">> = Specific
  const handler = {} as typeof import("../../src/app/tools/[toolUuid]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools">> = Specific
  const handler = {} as typeof import("../../src/app/tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/usage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/usage">> = Specific
  const handler = {} as typeof import("../../src/app/usage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workflow/[workflowId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflow/[workflowId]">> = Specific
  const handler = {} as typeof import("../../src/app/workflow/[workflowId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workflow/[workflowId]/run/[runId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflow/[workflowId]/run/[runId]">> = Specific
  const handler = {} as typeof import("../../src/app/workflow/[workflowId]/run/[runId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workflow/[workflowId]/runs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflow/[workflowId]/runs">> = Specific
  const handler = {} as typeof import("../../src/app/workflow/[workflowId]/runs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workflow/[workflowId]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflow/[workflowId]/settings">> = Specific
  const handler = {} as typeof import("../../src/app/workflow/[workflowId]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workflow/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflow/create">> = Specific
  const handler = {} as typeof import("../../src/app/workflow/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workflow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflow">> = Specific
  const handler = {} as typeof import("../../src/app/workflow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/oss/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/oss">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/oss/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/config/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/config/auth">> = Specific
  const handler = {} as typeof import("../../src/app/api/config/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/config/latest-version/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/config/latest-version">> = Specific
  const handler = {} as typeof import("../../src/app/api/config/latest-version/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/config/posthog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/config/posthog">> = Specific
  const handler = {} as typeof import("../../src/app/api/config/posthog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/config/sentry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/config/sentry">> = Specific
  const handler = {} as typeof import("../../src/app/api/config/sentry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/config/version/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/config/version">> = Specific
  const handler = {} as typeof import("../../src/app/api/config/version/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/impersonate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/impersonate">> = Specific
  const handler = {} as typeof import("../../src/app/impersonate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
