import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const docs = resolve(root, 'docs');
const spec = JSON.parse(readFileSync(resolve(docs, 'api-reference/openapi.json'), 'utf8'));
const configPath = resolve(docs, 'docs.json');
const config = JSON.parse(readFileSync(configPath, 'utf8'));
const check = process.argv.includes('--check');
const methods = new Set(['get', 'post', 'put', 'patch', 'delete', 'head', 'options']);
const groups = new Map();
const generated = new Set();
let stale = false;

function resourceGroup(path) {
  if (path.includes('/text-chat/')) return 'Text chat and scenarios';
  if (path.includes('/embed')) return 'Website embeds';
  if (/\/organizations\/(usage|billing)\//.test(path)) return 'Billing and usage';
  if (path.includes('/organizations/reports/')) return 'Reports';
  if (/\/organizations\/telephony/.test(path)) return 'Telephony configuration';
  if (path.includes('/user/api-keys')) return 'API keys';
  if (path.includes('/user/service-keys')) return 'Service Keys';
  const resource = path.replace(/^\/api\/v1\//, '').split('/')[0];
  return {
    workflow: 'Agents and runs', campaign: 'Campaigns', credentials: 'Credentials',
    tools: 'Tools', organizations: 'Workspace configuration', user: 'User configuration',
    public: 'Public calls and artifacts', 'voice-clones': 'Voice cloning',
    'knowledge-base': 'Knowledge base', 'workflow-recordings': 'Recordings',
    folder: 'Folders', 'node-types': 'Node schemas', health: 'Health',
    s3: 'Storage', telephony: 'Outbound calls', turn: 'TURN', docs: 'Documentation assistant',
  }[resource] ?? resource;
}

function save(path, text) {
  if (check) {
    let current;
    try { current = readFileSync(path, 'utf8'); } catch { current = ''; }
    const matches = path === configPath && current
      ? JSON.stringify(JSON.parse(current)) === JSON.stringify(JSON.parse(text))
      : current === text;
    if (!matches) { console.error(`Out of date: ${path}`); stale = true; }
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, text);
  }
}

// Provider callbacks, superuser administration, and local sign-in are not
// application-integration APIs. Retain them in the authoritative full spec.
for (const [path, item] of Object.entries(spec.paths)) {
  if (/^\/api\/v1\/(superuser|auth|webhooks)\//.test(path)) continue;
  if (path.startsWith('/api/v1/telephony/') && !path.endsWith('/initiate-call')) continue;
  for (const [method, operation] of Object.entries(item)) {
    if (!methods.has(method)) continue;
    const tag = resourceGroup(path);
    const title = operation.summary ?? `${method.toUpperCase()} ${path}`;
    const slug = `${method}-${path.replace(/^\/api\/v1\//, '').replaceAll(/[{}]/g, '').replaceAll(/[^a-zA-Z0-9]+/g, '-').replace(/-$/, '')}`;
    const route = `api-reference/endpoints/${slug}`;
    if (generated.has(route)) throw new Error(`Duplicate endpoint route: ${route}`);
    generated.add(route);
    const body = `---\ntitle: ${JSON.stringify(title)}\ndescription: ${JSON.stringify(`${method.toUpperCase()} ${path} — request parameters and responses from the Menace Voice API schema.`)}\nopenapi: ${JSON.stringify(`${method.toUpperCase()} ${path}`)}\n---\n\n{/* Generated by scripts/sync_docs_api.mjs. Edit the API schema source to change the contract. */}\n\nSee [authentication](/api-reference/authentication) for workspace API access. Public embed and artifact endpoints use their documented session or access tokens.\n`;
    save(resolve(docs, `${route}.mdx`), body);
    if (!groups.has(tag)) groups.set(tag, []);
    groups.get(tag).push({ title, route, method, path });
  }
}

const sections = [...groups].sort(([a], [b]) => a.localeCompare(b));
const catalog = sections.map(([tag, entries]) => `## ${tag}\n\n${entries.map((entry) => `- [${entry.title}](/${entry.route}) — \`${entry.method.toUpperCase()} ${entry.path}\``).join('\n')}`).join('\n\n');
save(resolve(docs, 'api-reference/catalog.mdx'), `---\ntitle: "API catalog"\ndescription: "Browse the complete application API by resource, generated from the checked-in FastAPI schema."\n---\n\nThis catalog covers ${generated.size} application operations in the checked-in schema. The specialized guides explain multi-step workflows; each endpoint page supplies its request and response contract. Provider callbacks, superuser administration, and local authentication routes remain in the full OpenAPI file and are not promoted as application APIs here.\n\n${catalog}\n`);
const apiTab = config.navigation.tabs.find((tab) => tab.tab === 'API Reference');
apiTab.groups = apiTab.groups.filter((group) => group.group !== 'Complete endpoint reference');
apiTab.groups.push({ group: 'Complete endpoint reference', pages: sections.map(([tag, entries]) => ({ group: tag, pages: entries.map((entry) => entry.route) })) });
save(configPath, `${JSON.stringify(config, null, 2)}\n`);
// Detect removed operations explicitly; do not silently retain stale contracts.
const endpointDir = resolve(docs, 'api-reference/endpoints');
try {
  for (const file of readdirSync(endpointDir)) {
    if (file.endsWith('.mdx') && !generated.has(`api-reference/endpoints/${file.slice(0, -4)}`)) {
      console.error(`Remove stale generated endpoint: ${file}`); stale = true;
    }
  }
} catch (error) { if (error.code !== 'ENOENT') throw error; }
if (stale) process.exitCode = 1;
else console.log(`API catalog ${check ? 'is current' : 'generated'}: ${generated.size} operations.`);
