import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// The custom in-app documentation remains the source for these shared guides.
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const articles = JSON.parse(readFileSync(resolve(root, 'ui/src/lib/docs/articles.json'), 'utf8'));
const check = process.argv.includes('--check');
const escape = (text) => text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('{', '&#123;').replaceAll('}', '&#125;');
let stale = false;

for (const [mode, pages] of Object.entries(articles)) {
  for (const page of pages) {
    const blocks = page.blocks.map((block) => {
      switch (block.type) {
        case 'heading': return `## ${escape(block.text)}`;
        case 'paragraph': return escape(block.text);
        case 'list': return block.items.map((item) => `- ${escape(item)}`).join('\n');
        case 'callout': return `> **${escape(block.title)}**\n>\n${escape(block.text).split('\n').map((line) => `> ${line}`).join('\n')}`;
        case 'link': {
          const targetMode = block.mode ?? mode;
          if (!articles[targetMode]?.some((target) => target.slug === block.slug)) {
            throw new Error(`Unknown handbook link: ${targetMode}/${block.slug}`);
          }
          return `${escape(block.before)}[${escape(block.label)}](/handbook/${targetMode}/${block.slug})${escape(block.after ?? '')}`;
        }
        case 'code': {
          const fence = '`'.repeat(Math.max(2, ...(block.code.match(/`+/g) ?? []).map((run) => run.length)) + 1);
          const language = /^[a-z0-9_-]+$/i.test(block.language) ? block.language.toLowerCase() : 'text';
          return `${fence}${language}\n${block.code}\n${fence}`;
        }
        default: throw new Error(`Unsupported block: ${block.type}`);
      }
    });
    const content = `---\ntitle: ${JSON.stringify(page.title)}\ndescription: ${JSON.stringify(page.description)}\n---\n\n{/* Generated by scripts/sync_docs_handbook.mjs from the preserved in-app docs. */}\n\n${blocks.join('\n\n')}\n`;
    const path = resolve(root, 'docs/handbook', mode, `${page.slug}.mdx`);
    if (check) {
      let current;
      try { current = readFileSync(path, 'utf8'); } catch { current = ''; }
      if (current !== content) { console.error(`Out of date: ${path}`); stale = true; }
    } else {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, content);
    }
  }
}
if (stale) process.exitCode = 1;
else console.log(`Handbook ${check ? 'is current' : 'generated'}: ${Object.values(articles).flat().length} pages.`);
